### ISSUE TITLE
Force webview to open urls inside application

### ISSUE THREAD

**Issue by FredRDewitt** [imrankst1221/website-in-webview-with-admob#3]
How to force WebView to open all the urls inside the application?

**Comment by gesquivelob** [comment]
is this feature enabled in pro version?

**Comment by imrankst1221** [comment]
To open all the URL inside only call this line
`view.loadUrl(url);` on  `shouldOverrideUrlLoading()`

**Comment by imrankst1221** [comment]
> is this feature enabled in pro version?

Yes, the pro version has a lot of customization and you don't vent need any coding knowledge.
